import Section from '@/components/Section'
import PageHeader from '@/components/PageHeader'
import { Heart } from 'lucide-react'

export const metadata = { title: 'Donors — AMAL', description: 'Your generosity deserves proof.' }

export default function Page() {
  const whatYouGet = [
    'End‑to‑end visibility: See funds move from you → vault → recipient → impact.',
    'Stable value: Your donation converts into a stablecoin that maintains purchasing power.',
    'Secure distribution: Milestone‑based releases ensure funds reach the right hands.',
    'Long‑term purpose: Idle balances earn yield to support future giving.',
  ]

  const howToDonate = [
    'Choose a verified campaign from our platform.',
    'Select your payment method (card, bank, crypto).',
    'Funds convert to AMAL and allocate to the campaign vault.',
    'Receive real‑time updates, milestone alerts and impact reports.',
  ]

  const tracking = [
    'Vault balance and collateral backing.',
    'Release schedule and milestone progress.',
    'Yield generated by idle funds supporting future projects.',
    'Final outcomes and real‑world results delivered.',
  ]

  const whyChoose = [
    'Minimise wastage — lower overheads than traditional platforms.',
    'Maximise assurance — full transparency, no “black box” use.',
    'Multiply impact — the system reinvests idle capital.',
    'Global reach — give easily across borders and currencies.',
  ]

  return (
    <>
      <PageHeader
        title="Your generosity deserves more than hope — it deserves proof."
        kicker="Donors"
        icon={<Heart className="w-3.5 h-3.5" />}
        description={<>At AMAL, donors receive full visibility, stable value, and assurance that funds are working now and tomorrow.</>}
      />

      <Section narrow>
        <h2 className="h2">What You Get</h2>
        <div className="mt-4 grid gap-4 md:grid-cols-2">
          {whatYouGet.map((t) => (
            <div key={t} className="card p-5 text-[#0F172A]/80">{t}</div>
          ))}
        </div>
      </Section>

      <Section narrow>
        <h2 className="h2">How to Donate</h2>
        <ol className="mt-4 grid gap-3 max-w-5xl mx-auto">
          {howToDonate.map((t, i) => (
            <li key={t} className="card p-5">{i + 1}. {t}</li>
          ))}
        </ol>
      </Section>

      <Section narrow>
        <h2 className="h2">Tracking Impact</h2>
        <div className="mt-4 grid gap-4 md:grid-cols-2">
          {tracking.map((t) => (
            <div key={t} className="card p-5 text-[#0F172A]/80">{t}</div>
          ))}
        </div>
      </Section>

      <Section narrow>
        <h2 className="h2">Why Donors Choose AMAL</h2>
        <div className="mt-4 grid gap-4 md:grid-cols-2">
          {whyChoose.map((t) => (
            <div key={t} className="card p-5 text-[#0F172A]/80">{t}</div>
          ))}
        </div>
      </Section>

      <Section narrow>
        <div className="card p-6 md:p-8 text-center">
          <h3 className="h3">Join the Community</h3>
          <p className="mt-2 text-[#0F172A]/80 max-w-2xl mx-auto">Become part of a giving ecosystem where every donor is also a steward. Explore campaigns, connect with impact stories, and watch how your generosity becomes lasting change.</p>
          <div className="mt-4 inline-flex gap-3">
            <a href="/how-it-works" className="btn-primary">See How It Works</a>
            <a href="/contact" className="btn-outline">Get Started</a>
          </div>
        </div>
      </Section>
    </>
  )
}


